### PR TITLE
Revamped azslc 1.8.15 to rev2

### PR DESCRIPTION
**Pull request by galibzon**
because rev1 packages for all OSes endup
building from the wrong tags.

### CODE REVIEW

**Review by rgba16f — APPROVED** [review]

**Comment by rgba16f** [comment]
Where's the PR to update the tags azslc pulls from?

**Comment by spham-amzn** [comment]
I dont see any changes other than the revision bump

**Comment by galibzon** [comment]
> Where's the PR to update the tags azslc pulls from?

The correct tag was already defined in the previous PR. It was the package generation that went wrong, and not sure how it happened. This time around I uncompressed the generated packages to make sure `azslc --version` outputs 1.8.15

**Comment by galibzon** [comment]
> I dont see any changes other than the revision bump

Revision bump is all what is needed. For whatever reason the previous packages picked the wrong github tag. This time around is working, so only a rev bump is required and will do the same bump change in the engine so it picks the correct packages when the user configures.

**Review by spham-amzn — APPROVED** [review]

**Pull request merged**
