### PR TITLE
Script updates for assimp-5.2.5 on Linux aarch64 (ARM64)

### PR DESCRIPTION
**Pull request by spham-amzn**
Script updates for *assimp-5.1.6 on Linux aarch64 (ARM64)

**Build Command**
```
python3 ../3p-package-scripts/o3de_package_scripts/build_package.py --search_path . assimp-5.1.6-rev2-linux-aarch64
```

**Build output**
```
Creating/Updating package: assimp-5.2.5-rev1-linux-aarch64
    Adding files to: "./packages/temp/temp_package_assimp-5.2.5-rev1-linux-aarch64"
    Created: ./packages/assimp-5.2.5-rev1-linux-aarch64.tar.xz
    Created: ./packages/assimp-5.2.5-rev1-linux-aarch64.tar.xz.SHA256SUMS
    Created: ./packages/assimp-5.2.5-rev1-linux-aarch64.tar.xz.content.SHA256SUMS
    Created: ./packages/assimp-5.2.5-rev1-linux-aarch64.PackageInfo.json
    - Validating package: assimp-5.2.5-rev1-linux-aarch64 in folder ./packages....
    Package Hash: 62cb927e54ea7d7fb6a8df4996ca961108865c4aebdd6a2013daf70f985efe61 *assimp-5.2.5-rev1-linux-aarch64.tar.xz

```

**Upload output**
```
Using bucket: ly-dev-3p-packages
Package: assimp-5.2.5-rev1-linux-aarch64 ...
    - Validating package: assimp-5.2.5-rev1-linux-aarch64 in folder ./packages....
    - Uploading assimp-5.2.5-rev1-linux-aarch64.tar.xz...
    - Uploading assimp-5.2.5-rev1-linux-aarch64.tar.xz.SHA256SUMS...
    - Uploading assimp-5.2.5-rev1-linux-aarch64.tar.xz.content.SHA256SUMS...
    - Uploading assimp-5.2.5-rev1-linux-aarch64.PackageInfo.json...
    - Uploaded package assimp-5.2.5-rev1-linux-aarch64.
```

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

**Review by AMZN-stankowi — APPROVED** [review]

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by lawsonamzn — APPROVED** [review]

**Comment by spham-amzn** [comment]
Unfortunately, we have to disable a couple of unit tests that are failing only in aarch64 builds. They appear related to float precision, we will need to investigate in the future

**Comment by lumberyard-employee-dm** [comment]
> Unfortunately, we have to disable a couple of unit tests that are failing only in aarch64 builds. They appear related to float precision, we will need to investigate in the future

Is there a corresponding PR for that?

**Comment by spham-amzn** [comment]
This will not make it into the first milestone for arm64 since we are only only supporting non-tool ( server ) clients anyways. I did see this package built on arm64 elsewhere but there is not mention of any aarch64 build commands or arguments. That said, I'll creat an issue so we can circle back on this. For now I'm reverting the disabling of the failing unit tests

**Comment by spham-amzn** [comment]
Interestingly enough, the [build log](https://launchpadlibrarian.net/464753354/buildlog_ubuntu-focal-arm64.assimp_5.0.1~ds0-1build1_BUILDING.txt.gz) from ubuntu-focal's assimp-arm64 package shows that tests are not built nor ran as part of their packaging

**Comment by spham-amzn** [comment]
Ended up finding out the root cause for the failing tests was related to FP precision differences between x86 and arm64, which based on research can be alleviated with setting `fp-contract=off`

**Review by lawsonamzn — APPROVED** [review]

**Pull request merged**
