### PR TITLE
Converted pybind11 to 3p package source.

### PR DESCRIPTION
**Pull request by cgalvan**
Converted pybind11 package to pull from the github tag of v2.4.3 (matching the existing build of pybind11 being used currently). Tested locally and verified the pybind11 package is properly created.

Signed-off-by: Chris Galvan <chgalvan@amazon.com>

### CODE REVIEW

**Review by AMZN-daimini — APPROVED** [review]

**Comment by lawsonamzn** [comment]
Just checking in here, it has enough approvals.  What's next?

**Comment by cgalvan** [comment]
> Just checking in here, it has enough approvals. What's next?

I think I just need to resolve the conflicts then re-push!

**Comment by lawsonamzn** [comment]
This is starting to block other projects, such as opencolorio/openimageio conversion.

**Comment by lawsonamzn** [comment]
Do you want me to try to take this over?  I can probably take it from here.

**Comment by cgalvan** [comment]
> Do you want me to try to take this over? I can probably take it from here.

Sure! Sorry I hadn't circled back to this, really we just need to fix the merge conflict and then upload new binary packages

**Review by jackalbe — APPROVED** [review]

**Comment by lawsonamzn** [comment]
thanks for the signoff.  Currently doing local testing.

**Pull request merged**
